# Generated by Django 5.2.1 on 2025-06-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
